baseURL = "http://example.org/"
languageCode = "en-us"
title = "My Academyza Hugo"
theme = "academyza-hugo"

[params.author]
name = "sholehud"
url = "https://sholeh.space"

[params.company]
name = "academyza"
shortname = "academyza"
description = "academyza website free for our school"
keywords = "website, company, school"
email = "company@email.com"
phone = "+62 811 123 456"

[params.hero]
heading = "Welcome to Academyza"
subheading = "The right place for learn Anything."